### ISSUE TITLE
Code Generation Options - Allow Overriding Scalar Type Definitions 

### ISSUE THREAD

**Issue by WonderPanda** [remorses/genql#40]
It would be awesome to have more options available to developers to allow more control over the code generation process.

The [GraphQL Code Generator plugin for React Apollo](https://graphql-code-generator.com/docs/plugins/typescript-react-apollo) allows for overriding the underlying TS types that are given to custom scalars. Eg:

```
config:
  scalars:
    DateTime: Date
    JSON: "{ [key: string]: any }"
    uuid: string
```

Currently custom scalars all come out using the `any` type when a more logical built in TS type would be a better match.

@remorses I'm interested in helping to implement this feature if you think it would be a good fit for the library
